ScoreSheet/config/routes.rb
Rails.application.routes.draw do

  get 'auth/login' => 'authentication#login'
  post 'auth/auth_login' => 'authentication#auth_login'
  post 'auth/auth_signin' => 'authentication#auth_signin'
  get 'auth/logout' => 'authentication#logout'

  root 'score_sheet#index'
  get 'score_sheet' => 'score_sheet#index'
  get 'score_sheet/index'
  get 'score_sheet/new'
  get 'score_sheet/edit'
  post 'score_sheet/create'
  patch 'score_sheet/:id/update' => 'score_sheet#update'
  get 'score_sheet/:id/delete' => 'score_sheet#destroy'

  resources :seasons
  resources :games
  resources :members
  get '/season/:season_id/members/no/:jersey_number' => 'members#show_jersey_no'

end

ScoreSheet/app/models/season.rb
class Season < ActiveRecord::Base

  def self.selected_season(id)
    if id.nil?
      last
    else
      find(id)
    end
  end

  def self.seasons_menu
    season0 = where('id >=  1 and 10 > id').select(:id, :season_name).order('id DESC')
    season1 = where('id >= 10 and 20 > id').select(:id, :season_name).order('id DESC')
    season2 = where('id >= 20 and 30 > id').select(:id, :season_name).order('id DESC')
    season3 = where('id >= 30 and 40 > id').select(:id, :season_name).order('id DESC')
    [season3, season2, season1, season0]
  end
end

ScoreSheet/app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params[:season]
    end
end

ScoreSheet/app/helpers/seasons_helper.rb
module SeasonsHelper
end

ScoreSheet/app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ScoreSheet/app/views/seasons/edit.html.erb
<h1>Editing season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

ScoreSheet/app/views/seasons/index.html.erb
<h4>Listing seasons</h4>
<div>
  <div class="row">
    <div class="col-md-6">
      <table class="table table-bordered table-striped">
        <thead>
            <tr>
              <th>Season Name</th>
              <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <% @seasons.each do |season| %>
              <tr>
                <td><%= season.season_name %></td>
                <td><%= link_to 'Show', season %></td>
                <td><%= link_to 'Edit', edit_season_path(season) %></td>
                <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>

<%= link_to 'New Season', new_season_path %>

ScoreSheet/app/views/seasons/new.html.erb
<h1>New season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

ScoreSheet/app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>