ScoreSheet/config/routes.rb
Rails.application.routes.draw do

  get 'auth/login' => 'authentication#login'
  post 'auth/auth_login' => 'authentication#auth_login'
  post 'auth/auth_signin' => 'authentication#auth_signin'
  get 'auth/logout' => 'authentication#logout'

  root 'score_sheet#index'
  get 'score_sheet' => 'score_sheet#index'
  get 'score_sheet/index'
  get 'score_sheet/new'
  get 'score_sheet/edit'
  post 'score_sheet/create'
  patch 'score_sheet/:id/update' => 'score_sheet#update'
  get 'score_sheet/:id/delete' => 'score_sheet#destroy'

  resources :seasons
  resources :games
  resources :members
  get '/season/:season_id/members/no/:jersey_number' => 'members#show_jersey_no'

end

ScoreSheet/app/models/admin.rb
class Admin < ActiveRecord::Base
end

ScoreSheet/app/models/division.rb
class Division < ActiveRecord::Base
  def self.last_div
    last
  end

  def self.my_div(id)
    where(id: id).last
  end
end

ScoreSheet/app/models/game.rb
class Game < ActiveRecord::Base
  #Association
  belongs_to :season
  belongs_to :division
  belongs_to :game_type

  belongs_to :team
  belongs_to :home_team, class_name:Team, foreign_key:'home_team_id'
  belongs_to :away_team, class_name:Team, foreign_key:'away_team_id'

  has_many :game_members
  has_many :member, through:'game_members'
  has_many :goals
  has_many :penalties, through:'game_penalties'

  #Method
  def self.selected_game(season_id, id)
    if season_id.nil? && id.nil?
      selected_game = all.order(:game_date,:game_time).last
    elsif season_id.nil? && id.present?
      selected_game = find(id)
    elsif season_id.present? && id.nil?
      selected_game = where(season_id:season_id).order(:game_date,:game_time).last
    else
      selected_game = where(season_id:season_id, id:id).order(:game_date,:game_time).last
    end
    selected_game.nil? ? all.order(:game_date,:game_time).last : selected_game
  end

  def self.games_navi(season_id)
    where(season_id:season_id).order(:game_date,:game_time)
  end

  #Validation
  validates :season_id, presence: {message:'は必須です。'}
  validates :division_id, presence: {message:'は必須です。'}
  validates :team_id, presence: {message:'は必須です。'}
  validates :game_type_id, presence: {message:'は必須です。'}
  validates :game_name, presence: {message:'は必須です。'}
  validates :game_date, presence: {message:'は必須です。'}
  validates :home_team_id, presence: {message:'は必須です。'}
  validates :away_team_id, presence: {message:'は必須です。'}

end

ScoreSheet/app/models/game_member.rb
class GameMember < ActiveRecord::Base
  #Association
  belongs_to :games
  belongs_to :member

  def self.game_goalies(game_id)
    where(game_id:game_id, goalie_flg: 1).limit(2)
  end

  def self.game_players(game_id)
    where(game_id:game_id, goalie_flg: 0).limit(15)
  end
end

ScoreSheet/app/models/game_penalty.rb
class GamePenalty < ActiveRecord::Base
  #Association
  belongs_to :game
  belongs_to :penalty
  belongs_to :member, class_name:Member, foreign_key:'penalty_member_id'

  def self.details(game_id)
    where(game_id: game_id).order('period, penalty_min, penalty_sec')
  end

end

ScoreSheet/app/models/game_type.rb
class GameType < ActiveRecord::Base
end

ScoreSheet/app/models/goal.rb
class Goal < ActiveRecord::Base
  #Association
  belongs_to :goal_member, class_name:Member, foreign_key:'goal_member_id'
  belongs_to :assist1_member, class_name:Member, foreign_key:'assist1_member_id'
  belongs_to :assist2_member, class_name:Member, foreign_key:'assist2_member_id'


  def self.details(game_id)
    where(game_id: game_id).order('period, goal_min, goal_sec').limit(15)
  end

end

ScoreSheet/app/models/member.rb
class Member < ActiveRecord::Base
  #Securty Option
  has_secure_password

  #Association
  belongs_to :position
  has_many :season_members

  #Methods
  def member_name
    attribute('last_name') + ' ' + attribute('first_name')
  end

  def self.authenticate(email, passwd)
    where(:email => email, :password_digest => passwd).first
  end

  def self.season_member(season_id, jersey_number)
    select('members.id as id, jersey_number as jersey_number, concat(last_name," ",first_name) as member_names, positions.position_name as position_name')
        .joins(:season_members, :position)
        .where('season_members.season_id'=>season_id)
        .where(jersey_number: jersey_number).last
  end
end

ScoreSheet/app/models/penalty.rb
class Penalty < ActiveRecord::Base

  #Association

  #Methods
  def self.penalties
    sql = 'select *
             from penalties P
             left join (select penalty_id,
                               count(penalty_id) as cnt
                          from game_penalties
                         group by penalty_id) G
              on P.id = G.penalty_id
           order by G.cnt DESC;'
    find_by_sql sql
  end
end

ScoreSheet/app/models/position.rb
class Position < ActiveRecord::Base
end

ScoreSheet/app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
end

ScoreSheet/app/models/season.rb
class Season < ActiveRecord::Base

  def self.selected_season(id)
    if id.nil?
      last
    else
      find(id)
    end
  end

  def self.seasons_menu
    season0 = where('id >=  1 and 10 > id').select(:id, :season_name).order('id DESC')
    season1 = where('id >= 10 and 20 > id').select(:id, :season_name).order('id DESC')
    season2 = where('id >= 20 and 30 > id').select(:id, :season_name).order('id DESC')
    season3 = where('id >= 30 and 40 > id').select(:id, :season_name).order('id DESC')
    [season3, season2, season1, season0]
  end
end

ScoreSheet/app/models/season_member.rb
class SeasonMember < ActiveRecord::Base
  #Association
  belongs_to :season
  belongs_to :division
  belongs_to :member

  def self.season_goalies(season_id)
    # joins(Member).where(season_id:season_id, position_id:3)
    sql = "select *
             from season_members S
             left join members M
               on S.member_id = M.id
            where M.position_id = 3
              and S.season_id = :season_id"
    find_by_sql([sql,{season_id:season_id}])
  end

  def self.season_players(season_id)
#    joins(Member).where(season_id:season_id).where.not(position_id:3)
    sql = "select *
             from season_members S
             left join members M
               on S.member_id = M.id
            where M.position_id <> 3
              and S.season_id = :season_id"
    find_by_sql([sql,{season_id:season_id}])
  end


end

ScoreSheet/app/models/season_team.rb
class SeasonTeam < ActiveRecord::Base

  #Association
  belongs_to :season
  belongs_to :division
  belongs_to :team

  def self.season_teams(season_id)
    sql = "select R.team_id team_id,
                  T.team_name team_name
             from season_teams R
             left join teams T
               on R.team_id = T.id
            where R.season_id = :season_id "
    find_by_sql([sql, season_id:season_id])
  end
end

ScoreSheet/app/models/team.rb
class Team < ActiveRecord::Base
end

ScoreSheet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ScoreSheet/app/helpers/application_helper.rb
module ApplicationHelper
end

ScoreSheet/app/helpers/games_helper.rb
module GamesHelper
end

ScoreSheet/app/helpers/member_helper.rb
module MemberHelper
end

ScoreSheet/app/helpers/members_helper.rb
module MembersHelper
end

ScoreSheet/app/helpers/seasons_helper.rb
module SeasonsHelper
end

ScoreSheet/app/helpers/session_helper.rb
module SessionHelper
end

ScoreSheet/app/views/application/_games_navi.html.erb
<div>
  <ul class="nav nav-tabs" role="tablist">
    <% @games_navi.each do |game| %>
      <% if game.id == @game.id %>
        <li role="presentation" class="active">
      <% else %>
        <li role="presentation">
      <% end %>
            <%= link_to game.game_name, score_sheet_index_path(season_id:@game.season_id, game_id:game.id)%>
        </li>
    <% end %>
  </ul>
</div>

ScoreSheet/app/views/application/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Score Sheet', root_path, class:'navbar-brand'%>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to score_sheet_index_path(season_id:@season.id) do %>
            <%= @season.season_name %>
              (<%= @season.season_start %> 〜 <%= @season.season_end %>)
          <% end %>
        </li>
        <!--Dropdown Menu-->
        <% @seasons_menu.each do |seasons| %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%=seasons.max.season_name%>←<%=seasons.min.season_name%><span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% seasons.each do |season| %>
            <li>
              <%= link_to season.season_name, score_sheet_index_path(season_id:season.id) %>
            </li>
            <%end%>
          </ul>
        </li>
        <% end %>
        <!--// Dropdown Menu-->
      </ul>
      <!-- Member Info -->
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if session[:is_login] %>
              <%= link_to nil, class:'navbar-brand' do %>
                <span class="glyphicon glyphicon-user"></span>
                <%= session[:member_name]%>
              <% end %>
          <% else %>
              <%= link_to 'Login', auth_login_path, class:'navbar-brand' %>
          <% end %>
        </li>
        <li>
          <% if session[:is_login] %>
              <%= link_to auth_logout_path do %>
              <span class="label label-primary">
                    <span class="glyphicon glyphicon-log-out" aria-hidden="true">Logout</span>
              </span>
              <% end %>
          <% end %>
        </li>
      </ul>
      <!--// Member Info -->
    </div>
  </div>
</nav>